openapi: '3.0.0'
info:
  version: '1.0.0'
  title: 'Space Objects API'
  description: 'Space Objects API'
paths:
  /spacecrafts/{spacecraftId}:
    parameters:
      - name: spacecraftId
        description: The unique identifier of the spacecraft
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/SpacecraftId'
    get:
      summary: Read a spacecraft
      responses:
        200:
          description: The spacecraft corresponding to the provided `spacecraftId`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Spacecraft'
        404:
          description: No spacecraft found for the provided `spacecraftId`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /planets/{planetId}:
    parameters:
      - name: planetId
        description: The unique identifier of the planet
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/PlanetId'
    get:
      summary: Read a planet
      responses:
        '200':
          description: The plamet corresponding to the provided `planetId`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Planet'
        404:
          description: No planet found for the provided `planetId`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    SpacecraftId:
      description: The unique identifier of a spacecraft
      type: string
    Spacecraft:
      type: object
      required:
        - id
        - name
        - type
        - description
      properties:
        id:
          $ref: '#/components/schemas/SpacecraftId'
        name:
          type: string
        type:
          type: string
          enum:
            - capsule
            - probe
            - satellite
            - spaceplane
            - station
        description:
          type: string
    PlanetId:
      description: The unique identifier of a planet
      type: string
    Planet:
      type: object
      required:
        - id
        - name
        - type
        - description
      properties:
        id:
          $ref: '#/components/schemas/planetId'
        name:
          type: string
        type:
          type: string
          enum:
            - gas-giant
            - terrestial
            - super-earth
            - neptune-like
        description:
          type: string
    Error:
      type: object
      required:
        - message
      properties:
        message:
          description: A human readable error message
          type: string
  securitySchemes:
    ApiKey:
      type: apiKey
      in: header
      name: X-Api-Key
